version: "3.9"

services:
  backend:
    image: python:3.12-slim
    container_name: app-backend
    working_dir: /app
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    image: node:20-alpine
    container_name: app-frontend
    working_dir: /app
    env_file: .env
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      - CHOKIDAR_USEPOLLING=true   # помогает HMR на Docker Desktop/WSL
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - backend
